### ISSUE TITLE
It is possible to output the skeleton points?

### ISSUE THREAD

**Issue by BurguerJohn** [mks0601/I2L-MeshNet_RELEASE#10]
I see there is some numeric variables like 'mesh_param_img' but i'm note sure if this is correct to generate a skeleton representation of the 3D model.

**Comment by mks0601** [comment]
Could you specify your question? I can't understand

**Comment by BurguerJohn** [comment]
Sure no problem. I would like to get the keypoints that generate the 3D skeleton, like OpenPose generate a Json with the key points:
![pose_face_hands](https://user-images.githubusercontent.com/32472975/91469788-3dd88980-e86a-11ea-8514-ed4351aa4666.gif)

Something like.
Left Shoulder: X - 124.3 / Y - 85.3 / Z - 34.4
Left Elbow: X - 134.2 / Y - 90.4 / Z - 33.2

**Comment by mks0601** [comment]
Sure. You can use `joint_lixel_img = out['joint_coord_img']` and do the below lines.

**Comment by BurguerJohn** [comment]
Alright! Thank you very much, will give it a try later.
