### ISSUE TITLE
Question about coco_smplifyx_train.json

### ISSUE THREAD

**Issue by HyoKong** [mks0601/I2L-MeshNet_RELEASE#11]
Hi, thank you very much for your excellent job!

Is it feasible to convert the [MSCOCO 3d meshes](https://drive.google.com/drive/folders/1Dkb-q10O9S4gQgKhFTxEtlEPqFTy3GJV) to 3d skeleton? Could you please give me advice? Thank you very much for your help!

**Comment by mks0601** [comment]
Yes actually, the code is doing that. 
For the SMPL joint set (24 joints):
https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/cb785c34139ea7945b0b5dd351a097aa1ebdff1d/data/MSCOCO/MSCOCO.py#L143

For the COCO joint set (17 joints):
`np.dot(self.coco_joint_regressor, smpl_mesh_cam)`

You can projects the 3D coordinates to 2D image space by https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/cb785c34139ea7945b0b5dd351a097aa1ebdff1d/data/MSCOCO/MSCOCO.py#L227

**Comment by HyoKong** [comment]
Thank you very much for your reply!

**Comment by HyoKong** [comment]
Hi, here is another question. I've converted the coco 3d mesh to 3d skeleton. But the style of the coco 3d keypoints is different from the annotation style of H36M. How can convert the coco style to the H36M style? 
Thank you very much for your help!

**Comment by mks0601** [comment]
If you multiply `data/Human36M/J_regressor_h36m_correct.npy` to mesh, it produces H36M 3D joint coordinates.
If you multiply `data/MSCOCO/J_regressor_coco_hip_smpl.npy` to mesh, it produces MSCOCO 3D joint coordinates.

**Comment by HyoKong** [comment]
Thank you very much for your help! 
How did you obtain the smpl parameters of the MSCOCO train dataset? Could you please share the corresponding code?

**Comment by mks0601** [comment]
As I wrote in the paper and README, I used SMPLify-X (https://github.com/vchoutas/smplify-x).

**Comment by HyoKong** [comment]
Okay! I'm very grateful for your help!
