### ISSUE TITLE
"The file exceeds the download quota. " 

### ISSUE THREAD

**Issue by SuperJay1996** [mks0601/I2L-MeshNet_RELEASE#110]
I met this question "The file exceeds the download quota" when I download the H36M dataset images. There are other available dataset resource for download?

**Comment by mks0601** [comment]
![image](https://user-images.githubusercontent.com/13601723/158564539-17758d30-f3a9-4de9-b8e8-838c8ec6db1b.png)

**Comment by mks0601** [comment]
Please follow this instruction in the README

**Comment by SuperJay1996** [comment]
Thanks for your response, i'll try this follow the instruction in the README.

**Comment by SuperJay1996** [comment]
Thanks for your response, i'll try this follow the instruction in the README.
