### ISSUE TITLE
The provided freihand pose param is different from freihand origin dataset

### ISSUE THREAD

**Issue by EAST-J** [mks0601/I2L-MeshNet_RELEASE#114]
Hi, I download the origin mano params from the freihand. I found that the provided dataset have the different pose_param, but they have the same shape_params. I wonder what's the difference between them?

**Comment by mks0601** [comment]
That is related with 'flat_hand_mean' option of MANO. 
https://github.com/hassony2/manopth/blob/4f1dcad1201ff1bfca6e065a85f0e3456e1aa32b/manopth/manolayer.py#L34

**Comment by mks0601** [comment]
The first three params represent 3D root rotation (3D wrist rotation). The original FreiHAND dataset does not provide 3D root rotation in the camera-centered coordinate system. Instead, it provides 3D root rotation in the world-coordinate system. I obtained the 3D root rotation in the camera centered coordinate system by rigidly aligning 3D hand meshes to the provided 3D joint coordinates in the camera-centered coordinate system. That is why there is a small 3D root rotation difference.
