### ISSUE TITLE
bbox_root_freihand_output.json

### ISSUE THREAD

**Issue by Sibo2rr** [mks0601/I2L-MeshNet_RELEASE#121]
Hi! Thank you for your great work!
Could you please share the bbox_root_freihand_output.json file again? I remember you have attached a link for this file before, but that link is invalid now.

**Comment by mks0601** [comment]
Maybe this one?
https://github.com/mks0601/I2L-MeshNet_RELEASE#freihand-dataset

**Comment by Sibo2rr** [comment]
Thank you for your prompt reply!
