### ISSUE TITLE
KeyError: 'mesh_coord_cam'

### ISSUE THREAD

**Issue by ouusan** [mks0601/I2L-MeshNet_RELEASE#129]
Thanks for your work, it is so cool !!
I am trying to run the demo.py, but following error occurs:
Traceback (most recent call last):
  File "demo.py", line 106, in <module>
    mesh_param_cam = out['mesh_coord_cam'][0].cpu().numpy()
KeyError: 'mesh_coord_cam'

I print the out, it has only 'joint_coord_img','mesh_coord_img','bb2img_trans' , what's my problem, could you please tell me how can i solve it?

**Comment by mks0601** [comment]
as in here (https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/eae673ea0b5229c6c7c0ed6d24633f648683da5c/main/model.py#L115), you should set --stage param

**Comment by ouusan** [comment]
Thank you sooo much!! Now solved it
