### ISSUE TITLE
RootNet model for FreiHand ?

### ISSUE THREAD

**Issue by hassony2** [mks0601/I2L-MeshNet_RELEASE#16]
Hi @mks0601,

Thank you for the great work, I look forward to experimenting with it !
I want to try your model on some different hand images, and I was therefore wondering if you could share the model of the trained hand RootNet ? (I searched a link to such a pre-trained model both in this repo and https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE)

All the best !

Yana

**Comment by mks0601** [comment]
Hi @hassony2 ,

Great to see you! I used your manopth repo for my paper.
Unfortunately, I didn't save the RootNet trained on FreiHAND :(
The rootnet prediction results are available at [here](https://drive.google.com/drive/folders/1OzwQG2ZutJ4Lzg5psilStsv_MO6-cysA?usp=sharing) and parsed FreiHAND data is also available at [here](https://drive.google.com/drive/folders/1QGWu_nWi5eyrWSkPEOMyK1tAGFWRXQjC?usp=sharing), which are included in README.
If you need a pre-trained RootNet, I think you can train it easily using the RootNet repo and parsed FreiHAND data.

Thanks!
Gyeongsik

**Comment by hassony2** [comment]
Thank you @mks0601 for your prompt response !

I will look whether I need to retrain it in this case !


I am glad you found manopth useful :) Have a great day !

Yana
