### ISSUE TITLE
Questions about render effect

### ISSUE THREAD

**Issue by XiaoqiangZhou** [mks0601/I2L-MeshNet_RELEASE#19]
Thanks for your great work.

When I tried to run the 'quick demo' program, the rendered result I got looks a little plain/ordinary, like 'assets/video2.gif'.  There isn't much texture or light difference in different human parts.
I hope to get the effect like result in 'assets/qualitative results.png', which has rich texture and shadow diversity in the rendered result.

Could you please me how to achieve such effect? I tried to change the 'metallicFactor' and 'color' parameter in 'render_mesh' of 'vis.py', but it doesn't help.

By the way, this is my "plain result", which just looks like a 2D segmentation results instaed of 3D rendered result.
![mesh_r_0 40_g_0 20_b_0 00](https://user-images.githubusercontent.com/28076886/93858960-8cedcf00-fcef-11ea-9f3d-f48fed003557.jpg)

**Comment by mks0601** [comment]
As you said, the `render_mesh` function in `vis.py` may output some plain rendered results. However, your result looks very extreme case hmm.. did you change any parameters from my settings?

The `assets/qualitative result.png` is actually from [Open3D](https://github.com/intel-isl/Open3D), but it is quite annoying to use this actually... so I changed the codes to much simpler one, which is current `render_mesh` function in `vis.py`. 

Could you try mesh rendering from my setting in `render_mesh` function? Or you can try open3d, but it is quite annoying to use that as I said :(

**Comment by XiaoqiangZhou** [comment]
Thanks for your quick reply and kind suggestion.

In fact, I just change the render color in `render_mesh` function in `vis.py`. We find the reason of plain rendered effect is the image itself, which is captuerd in indoor environment and the image quality is realtively low. When we use image in the `demo` folder, it becomes much better.

Thanks for your advice. We may consider to use Open3D in the future if necessary.
