### ISSUE TITLE
Undefined names in Python code -- missing imports?

### ISSUE THREAD

**Issue by cclauss** [mks0601/I2L-MeshNet_RELEASE#2]
[flake8](http://flake8.pycqa.org) testing of https://github.com/mks0601/I2L-MeshNet_RELEASE on Python 3.9.0rc1+

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./main/test.py:22:23: F821 undefined name 'mem_info'
        gpus[1] = len(mem_info()) if not gpus[1].isdigit() else int(gpus[1]) + 1
                      ^
./main/train.py:20:23: F821 undefined name 'mem_info'
        gpus[1] = len(mem_info()) if not gpus[1].isdigit() else int(gpus[1]) + 1
                      ^
./common/utils/manopth/manopth/tensutils.py:46:5: F821 undefined name 'List'
    # type: (List[int]) -> List[int]
    ^
./common/utils/manopth/manopth/tensutils.py:46:5: F821 undefined name 'List'
    # type: (List[int]) -> List[int]
    ^
./common/utils/manopth/manopth/rodrigues_layer.py:83:31: F821 undefined name 'th_cv2_rod_sub_id'
    test_function = gradcheck(th_cv2_rod_sub_id.apply, (inputs_var, ))
                              ^
./common/utils/manopth/manopth/rodrigues_layer.py:88:25: F821 undefined name 'th_cv2_rod'
    test_th = gradcheck(th_cv2_rod.apply, (inputs_var, ))
                        ^
./common/utils/manopth/mano/webuser/serialization.py:22:1: F822 undefined name 'save_model' in __all__
__all__ = ['load_model', 'save_model']
^
./common/utils/manopth/mano/webuser/serialization.py:38:5: F821 undefined name 'backwards_compatibility_replacements'
    backwards_compatibility_replacements(dd)
    ^
./common/utils/smplpytorch/smplpytorch/pytorch/tensutils.py:52:5: F821 undefined name 'List'
    # type: (List[int]) -> List[int]
    ^
./common/utils/smplpytorch/smplpytorch/pytorch/tensutils.py:52:5: F821 undefined name 'List'
    # type: (List[int]) -> List[int]
    ^
./common/utils/smplpytorch/smplpytorch/pytorch/rodrigues_layer.py:79:31: F821 undefined name 'th_cv2_rod_sub_id'
    test_function = gradcheck(th_cv2_rod_sub_id.apply, (inputs_var, ))
                              ^
./common/utils/smplpytorch/smplpytorch/pytorch/rodrigues_layer.py:84:25: F821 undefined name 'th_cv2_rod'
    test_th = gradcheck(th_cv2_rod.apply, (inputs_var, ))
                        ^
./demo/demo.py:38:23: F821 undefined name 'mem_info'
        gpus[1] = len(mem_info()) if not gpus[1].isdigit() else int(gpus[1]) + 1
                      ^
./data/PW3D/PW3D.py:75:36: F821 undefined name 'joint_cam'
                root_joint_depth = joint_cam[self.root_joint_idx][2]
                                   ^
13    F821 undefined name 'backwards_compatibility_replacements'
1     F822 undefined name 'save_model' in __all__
14
```
https://flake8.pycqa.org/en/latest/user/error-codes.html

On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead, these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python, they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where __a == b__ is True but __a is b__ is False (or vice versa).  Python >= 3.8 will raise SyntaxWarnings on these instances.
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python, a __NameError__ is raised which will halt/crash the script on the user.

**Comment by mks0601** [comment]
Hi, great thanks for sanity checking of my codes!

I modified `mem_info` and `root_joint_depth` bugs, which are my mistakes.
However, `smplpytorch` and `manopth` are not my codes (they are from [smplpytorch](https://github.com/gulvarol/smplpytorch) and [manopth](https://github.com/hassony2/manopth), respectively, as described in README), so it is hard to modify them.
On my side, there is no crash from smplpytorch and manopth, so I think you can run my code without crash on your side too.
