### ISSUE TITLE
Question regarding camera extrinsics for FreiHand

### ISSUE THREAD

**Issue by pablovela5620** [mks0601/I2L-MeshNet_RELEASE#20]
The original FreiHand dataset only included the camera instrisic parameters (focal, princpt) and the principal point seems to be different from the original (looks like its half the image height/width vs whatever the calibrated parameters where). How did you go about finding the extrinsic parameters (R, t, scale)?

**Comment by mks0601** [comment]
1. Obtain 3D hand joint coordinates from MANO parameters
2. Load camera-centered 3D hand joint coordinates from `training_xyz.json`
3. Calculate R and t by the [rigid align algorithm](https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/e1937b00f4df93eeeabf205e2719d43c179b5abf/common/utils/transforms.py#L43).

**Comment by pablovela5620** [comment]
Perfect, thank you!
