### ISSUE TITLE
pseudo smpl parameter

### ISSUE THREAD

**Issue by seonghyunkim1212** [mks0601/I2L-MeshNet_RELEASE#24]
Thank you for your awesome work!

I have a question.
I know that the smpl pseudo gt paramter provided in this repository was obtained by fitting it to smplify-x.
Is it reasonable to use the provided pseudo gt in the smpl model?

**Comment by mks0601** [comment]
Could you clarify your question? I can't understand :( You can use Korean if you want

**Comment by seonghyunkim1212** [comment]
![1](https://user-images.githubusercontent.com/54994917/96086384-3abe5900-0efd-11eb-93af-a34d32381337.png)
![2](https://user-images.githubusercontent.com/54994917/96086388-3c881c80-0efd-11eb-9de7-098082403128.png)
![2](https://user-images.githubusercontent.com/54994917/96086389-3d20b300-0efd-11eb-8153-8ab65b6f5ab1.png)
![1](https://user-images.githubusercontent.com/54994917/96086390-3d20b300-0efd-11eb-9399-8d8627915c5e.png)

이 repo에서 제공하는 SMPL 파라미터를 SMPL layer에 input해서 얻은 3D joint인데요.
rotation이 맞는 것 같지 않아서요.. 넣기 전에 먼저 프로세싱을 해줘야하는 건가요??
그리고 pose parameter의 left hand와 right hand가 0으로 annotation되어있는데
smplify-x로 fitting시켜서 0으로 annotation된건가요?

**Comment by mks0601** [comment]
camera-centered coordinate이 아니라 world coordinate에 fit시켰기 때문에 각  camera-centered coordinate으로 extrinsic (rotation + translation)을 곱해줘서 옮겨야 합니다. [link](https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/21a8930d8c0a8815565940f9c5714d43cc0fe9c8/data/Human36M/Human36M.py#L172), [link2](https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/21a8930d8c0a8815565940f9c5714d43cc0fe9c8/data/Human36M/Human36M.py#L195).

smpl body model은 body만 modeling하기 때문에 hand는 0으로 되어있습니다 또 h36m joint중에 finger가 없기도하구요

**Comment by seonghyunkim1212** [comment]
네 답변 감사합니다.

smplify fitting으로 뽑은 smpl shape 파라미터와 이 repo에서 제공하는 shape 파라미터 10개는 같은 형식인가요?

**Comment by mks0601** [comment]
네 같습니다

**Comment by seonghyunkim1212** [comment]
네 답변 감사합니다!
