### ISSUE TITLE
Thans for your great work, if I want to predict the  regression coordinates of 3D human pose through network, the 3D ground truth is  the targets['orig_joint_img'] or  targets['fit_joint_img']? How do I figure the loss?

### ISSUE THREAD

**Issue by PuJanhan** [mks0601/I2L-MeshNet_RELEASE#30]

**Comment by mks0601** [comment]
`targets['orig_joint_img']` is calculated between output 3D pose and GT 3D pose of the dataset.
`targets['fit_joint_img']` is calculated between output 3D pose and 3D pose from the SMPL fits.
