### ISSUE TITLE
Recover MANO pose/shape parameters from model outputs

### ISSUE THREAD

**Issue by pablovela5620** [mks0601/I2L-MeshNet_RELEASE#31]
So I wanted to ask how one goes about getting the mano pose/shape parameters from the network output so that we can use outputs for graphics applications for joint angles and to ensure length preservation. As I see it there are two methods I can think of and didn't know if there was something I was missing

1. Training a param regressor head (seems like you've done this already for SMPL parameters but not for MANO). A similar approach to [this repo](https://github.com/CalciferZh/minimal-hand)
2. Using inverse kinematics with something like a Levenberg-Marquart solver. Like [this](https://github.com/CalciferZh/Minimal-IK) or the [MEgATrack paper](https://research.fb.com/publications/megatrack-monochrome-egocentric-articulated-hand-tracking-for-virtual-reality/)

Is there anything I'm missing? Either way, I appreciate all the help given so far

**Comment by mks0601** [comment]
Both are widely used, but I think the first one would be much better.
Performing IK with such kind of iterative solver takes a long running time, while easily be stuck in local minima.
You can try the parameter regressor of my code, or you can refer my very recent work, which will be uploaded at arxiv soon (in this week? or next week?).
My recent work outputs the pose/shape parameters, while its performance is better than I2L-MeshNet.

**Comment by pablovela5620** [comment]
That's awesome, I am always very impressed with all of the great work you've been putting out in the pose estimation space. I was originally leaning towards the regression method, because like you said not is it generally slower and prone to getting stuck in bad local minima's it's also annoyingly sensitive to initial conditions (which papers like SPIN deal with by merging the two and could be an interesting direction).

I'd had a change of mind when I read the MegaTrack paper, seeing how they're using an iterative solver on a real-time production system (oculus quest) but I'm not sure if the reason it's not as likely to bad local minima is due to it being a multi-camera system. 

I look forward to reading your latest work, having pose representation rather than verts/faces are more useful for applications but like you'd stated in this work you lose the spatial relationship and the ability to model uncertainty. Will be interested in seeing what you've come up with. It looks like a lot of the recent literature is directly regressing parameters (FrankMocap/Expose) in full human pose estimation.

**Comment by mks0601** [comment]
Great thanks! My recent works is for expressive 3D human pose and mesh that recovers face/hand/body simultaneously and outperform all available part-specific and expressive methods. Please stay tuned.

**Comment by mks0601** [comment]
Hi, my new work is available on [arxiv](https://arxiv.org/abs/2011.11534)
