### ISSUE TITLE
Can't download H3.6M image files due to 'download quota exceed'

### ISSUE THREAD

**Issue by yuxwind** [mks0601/I2L-MeshNet_RELEASE#32]
Thanks for sharing your great job! I tried to download H3.6M image files from https://drive.google.com/drive/folders/1cx_BuF0tDcNww5OY0pLPn8r8G00NtFag

However, it reports an error:
Download quota exceeds for this file. So you can't download it at this time.

Could you help to fix this problem? Thanks.

**Comment by mks0601** [comment]
There are instructions for this issue in README.
```
* Go the shared folder, which contains files you want to copy to your drive  
* Select all the files you want to copy  
* In the upper right corner click on three vertical dots and select “make a copy”  
* Then, the file is copied to your personal google drive account. You can download it from your personal account.
```

**Comment by yuxwind** [comment]
Thanks!
