### ISSUE TITLE
Handling KeyError exceptions of smpl_params

### ISSUE THREAD

**Issue by andgitchang** [mks0601/I2L-MeshNet_RELEASE#34]
Hi,
I found there are indeed some keyerror exceptions of smpl_params as [you handled](https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/3fdee57b0203fcc9a94101c95baebd4465534c3b/data/Human36M/Human36M.py#L126). I'd like to realize how it will be processed when we call the function [get_smpl_coord](https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/3fdee57b0203fcc9a94101c95baebd4465534c3b/data/Human36M/Human36M.py#L167), since smpl_params are None. Is it feasible for me to manually populate zeros onto [smpl_param](https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/3fdee57b0203fcc9a94101c95baebd4465534c3b/data/Human36M/Human36M.py#L127)? Or just ignore this none smpl_param annotation? Thanks.

**Comment by mks0601** [comment]
Hi, you can see that when `smpl_param` is None, all variables related to `smpl_param` are set to zero tensors (see [here](https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/3fdee57b0203fcc9a94101c95baebd4465534c3b/data/Human36M/Human36M.py#L305)).
During the training, `smpl_joint_trunc`, `smpl_mesh_trunc`, `is_valid_fit` will make the loss from `smpl_param` zero.

**Comment by andgitchang** [comment]
I apologize I didn't trace the code thoroughly... Thanks for your explanation.
