### ISSUE TITLE
did anyone test it in realtime?

### ISSUE THREAD

**Issue by Hasankanso** [mks0601/I2L-MeshNet_RELEASE#36]
I wonder if someone has tested I2L-MeshNet on real time scenario...
I did that and I got poor fps and wrong mesh positioning. I tried it actually in a docker container, I've encountered many docker-related problems.

do you have any insight regarding I2L-MeshNet in real time scenario?

**Comment by mks0601** [comment]
Did you detect human first using an object detector? The input of I2L-MeshNet is a cropped human image.

**Comment by ferozkhanabbasi** [comment]
which file to run for the realtime?

**Comment by Hasankanso** [comment]
> which file to run for the realtime?

There's no such file in the repository. You have to integrate an object/person detection model like "yolo" and use it to extract persons, then crop them and feed them to the I2L-MeshNet model. you can put all these in openCV cam loop to get a real-time taste. but I believe it's too slow for real-time. Use demo/demo.py as a start point if you would.

Good luck
