### ISSUE TITLE
What FPS could we expect for the inference time?

### ISSUE THREAD

**Issue by Zrrr1997** [mks0601/I2L-MeshNet_RELEASE#37]
Have you done an estimation of the time it takes for the inference + rendering? Is it possible to use this model in real time applications, for example ~10 FPS? How much will the inference time increase if we have multiple people?

Let's say I am using YOLOv4 as a detection pipeline, so we can ignore the detection overhead.

**Comment by mks0601** [comment]
I2L-MeshNet runs at 50fps for each person as written in the paper. This time does not include the rendering, but I think rendering will take marginal time.
