### ISSUE TITLE
Evaluation FreiHAND

### ISSUE THREAD

**Issue by zqq-judy** [mks0601/I2L-MeshNet_RELEASE#39]
Hello. 
Would you like to share the evaluation code on the FreiHAND dataset, if it is convenient for you?
My email is 1573372947@qq.com .
Thank you！

![image](https://user-images.githubusercontent.com/40655640/105844396-23226080-6014-11eb-9d61-3ff89946976b.png)

**Comment by mks0601** [comment]
See here: https://github.com/mks0601/I2L-MeshNet_RELEASE#freihand-dataset
The evaluation on the output is performed at the official server (https://competitions.codalab.org/competitions/21238)
