### ISSUE TITLE
Cannot import name 'render_mesh'n from utils.viz

### ISSUE THREAD

**Issue by pablovela5620** [mks0601/I2L-MeshNet_RELEASE#4]
Looks like whenever the demo was updated to include the mesh rendering visualization, the accompanying render mesh function with utils.viz was not added. Getting the following error
``` bash
Traceback (most recent call last):
  File "/home/deeplearning/0Dev/repos/I2L-MeshNet_RELEASE/demo/demo.py", line 19, in <module>
    from utils.vis import vis_mesh, save_obj, render_mesh, optimize_camera
ImportError: cannot import name 'render_mesh' from 'utils.vis' (/home/deeplearning/0Dev/repos/I2L-MeshNet_RELEASE/main/../common/utils/vis.py)
```

**Comment by mks0601** [comment]
Sorry I have no idea why the function is not included in the `vis.py`. I added and the demo will run. Thanks!

**Comment by pablovela5620** [comment]
That was super quick! Thanks

**Comment by pablovela5620** [comment]
Also not sure if you would want to include in the requirements bash file but trimesh and pyrender are missing

**Comment by mks0601** [comment]
Changed requirements. Thanks!
