### ISSUE TITLE
Can this work generalize to half-portrait image?

### ISSUE THREAD

**Issue by hot-dog** [mks0601/I2L-MeshNet_RELEASE#40]
I tested snapshot_8.pth.tar with a half-portrait image which only contains torso and the above parts, it seems that the output_mesh_lixel.obj is also half-portrait and i think it should be correct, but the output_mesh_param.obj is full-portrait, it produces extra hip and legs part. Any suggestion? Thank you!

**Comment by mks0601** [comment]
As lixel-based heatmap is defined in the image space, it cannot recover area beyond images. On the other hand, param-based meshes are defined in 3D space. Therefore, it can always recover full body shape.

**Comment by hot-dog** [comment]
Thanks for your reply, i get it.
