### ISSUE TITLE
joint coordinate loss question

### ISSUE THREAD

**Issue by asw91666** [mks0601/I2L-MeshNet_RELEASE#42]
Hi, thanks for your great work.
The paper only says ||P-P*|| (8), but at the code, you used both GT joint coordinate and SMPL joint coordinate for predicting joint. so would you let me know why you use SMPL joint coordinate? Is GT joint an unreliable data?
thanks you.

https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/c940da098f42934e5726ec044d2960a4cd9ed141/main/model.py#L91

**Comment by mks0601** [comment]
The reason is that in-the-wild datasets, such as MSCOCO, do not provide 3D GT. SMPL joint coordinates are pseudo-GT 3D coordinates, so I'm using it.

**Comment by asw91666** [comment]
I see. thank you for quick reply !
