### ISSUE TITLE
How to Create 3D Human model from 2d Human Image? 

### ISSUE THREAD

**Issue by pixellib** [mks0601/I2L-MeshNet_RELEASE#43]
How to Create 3D Human model from 2d Human Image? 

Share sample code from your repo?

**Comment by mks0601** [comment]
I can't get your question.

**Comment by pixellib** [comment]
How to Generate 3D Obj Human Body ,from live camera [when human standing front of camera]?

**Comment by mks0601** [comment]
you can refer to this demo code
https://github.com/mks0601/I2L-MeshNet_RELEASE#quick-demo

**Comment by pixellib** [comment]
its not working , could you please share correct flow for to make 3d human body with live camera,
