### ISSUE TITLE
Speeding up network inference questions

### ISSUE THREAD

**Issue by pablovela5620** [mks0601/I2L-MeshNet_RELEASE#44]
I wanted to ask if you'd done any experimentation with a more mobile-friendly version of i2l.

I could image a few modifications to try to reduce the number of parameters and speed up network inference
1. Change backbone from Res50 to a smaller version (Res34/18)
2. Use a MobileNetV2/3backbone
3. Directly regress mesh lixel heatmaps rather than first getting pose lixel heatmaps -> feeding into another resnet + image feature

Have you done any of the following? It seems like some of these have been tried by implementations such as [Mediapipe face mesh regression method](https://google.github.io/mediapipe/solutions/face_mesh.html)

I also wanted to ask if you had any data on how integral regression and lixel based heatmap regression speed compares to traditional heatmap based methods.

Thanks!

**Comment by mks0601** [comment]
1,2: No I haven't.
3: There is a table in the paper which compares without and with pose regression.

**Comment by pablovela5620** [comment]
Whoops completely forgot that was in there. Had only remembered where you directly fed the ground truth 3d pose and not where you regressed. Thanks for the response. Here's the difference in the paper for anyone else that may wonder 
![image](https://user-images.githubusercontent.com/25287427/107684196-7d582e00-6c70-11eb-9070-7460b9428b23.png)
