### ISSUE TITLE
Can you provide the inference code for the video?

### ISSUE THREAD

**Issue by OOF-dura** [mks0601/I2L-MeshNet_RELEASE#46]
Can you provide the inference code for the video?
Like those showing in the demo :
![image](https://user-images.githubusercontent.com/22954901/108661321-7b129100-7506-11eb-91b8-b15383834921.png)

May I know the sources of the three videos?

**Comment by mks0601** [comment]
You can apply the demo codes on each frame.

**Comment by OOF-dura** [comment]
> You can apply the demo codes on each frame.

May I know the sources of the three videos?

**Comment by OOF-dura** [comment]
> You can apply the demo codes on each frame.

Sounds like this will cause some jitters.

**Comment by mks0601** [comment]
Source: https://virtualhumans.mpi-inf.mpg.de/3DPW/
The video results are obtained by applying my method on each frame.
