### ISSUE TITLE
about meta_info['is_3D']

### ISSUE THREAD

**Issue by asw91666** [mks0601/I2L-MeshNet_RELEASE#47]
Could i know why you use meta_info['is_3D']?
In model.py code, the meta_info['is_3D'] is used as input of "self.coord_loss" when GT is targets['orig_joint_img'].
But i think the code "class CoordLoss" seem no difference whether 'is_3D' is None or not None.
Is there anything i know wrong or don't know?

**Comment by mks0601** [comment]
All data from datasets with GT 3D pose (e.g., Human3.6M) have `is_3D=True`.
All data from datasets without GT 3D pose (e.g., MSCOCO) have `is_3D=False`.

**Comment by asw91666** [comment]
thank you !!
