### ISSUE TITLE
Some bounding box coordinates negative

### ISSUE THREAD

**Issue by Shubhendu-Jena** [mks0601/I2L-MeshNet_RELEASE#48]
Hi, 

Thank you for the great work. I had one doubt. Some of the bounding box coordinates that I am getting as output from "process_bbox" function are negative. Is this deliberate? One example of such an instance is for the image "s_05_act_04_subact_01_ca_04_003112.jpg". For this image, the bounding box origin coordinates, width and height are : 
array([ -6.87618172,  84.10320063, 606.78921781, 606.78921781]).
I found this out because I was trying to save the cropped images according to the bounding box coordinates.

Looking forward to your response

**Comment by mks0601** [comment]
Hi, as I'm using affine transformation to crop and resize the human image from the original image (see [here](https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/5d26ad43b9e68269721a80abe9e8a08e76e398d9/common/utils/preprocessing.py#L105)), the negative coordinates are not problems.

**Comment by Shubhendu-Jena** [comment]
Hi, thanks for the reply. Yes, it won't cause any problems regarding the re-sizing of course. I just wanted to know why the coordinates are negative. I was trying to save the cropped images inside the bounding box, hence I was facing this issue.

**Comment by mks0601** [comment]
Could you see the function at [here](https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/5d26ad43b9e68269721a80abe9e8a08e76e398d9/common/utils/preprocessing.py#L59)? It re-calculates coordinates based on scaled widths and heights.

**Comment by Shubhendu-Jena** [comment]
Hi, thanks again for the response. Got it. Closing issue.
