### ISSUE TITLE
Doubt regarding bounding box coordinates

### ISSUE THREAD

**Issue by Anirudh257** [mks0601/I2L-MeshNet_RELEASE#5]
I want to attain I2L rendered meshes for my dataset of images which involve more than 1 person. In your demo code, you have given some values for the bounding box of the input image

https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/f2cfe4d42baea7f85c618020455b43bbd0234d4a/demo/demo.py#L83

I have some images where multi-person are involved like this:
![image](https://user-images.githubusercontent.com/16001446/90431519-ccb90980-e0e6-11ea-85fa-05a7af1e6188.png)

Do I need to train the model again for the multiperson scenario with bounding box coordinates obtained via Fast-RCNN? Can you add the code for Fast-RCNN model? I am unable to find the relevant code in train.py

**Comment by mks0601** [comment]
1. obtain bbox coordinates using any human detection algorithm (my recommendation is [Detectron2](https://github.com/facebookresearch/detectron2))
2. make a loop in the demo code that iterates for each person and render meshes

**Comment by Anirudh257** [comment]
Thanks for the clarification
