### ISSUE TITLE
Can't download pretrained models!

### ISSUE THREAD

**Issue by Yarp96** [mks0601/I2L-MeshNet_RELEASE#51]
Hi, 
Im trying to download the pretrained models from https://drive.google.com/drive/folders/14SJKZuCudli2xNN6pSh1bJepIZYlBfSE however im getting the error: The number of downloads was exceeded.

Is there any other way to download pretrained models?

Best regards,

**Comment by Yarp96** [comment]
Thanks for the fast answer! Unfortunatly even after copying the model to my own drive it is still saying that the number of downloads was exceeded.

**Comment by mks0601** [comment]
Did you try download from your google drive file, not from the shared one?

**Comment by Yarp96** [comment]
Hi again,

Copying to my drive did not work however when I download the whole folder from my shared drive it zipped it and I was able to download it! 

Thank you for your time!

**Comment by Yarp96** [comment]
Sorry to bother again, I have been able to run the demo by following your steps however it seems like the output isn't what it should be and im not sure why. 

Here is a picture of the mesh on cloud compare: 
![image](https://user-images.githubusercontent.com/24324805/111340167-c4aa5380-864e-11eb-966d-2099748c55cd.png)
![output_mesh_lixel](https://user-images.githubusercontent.com/24324805/111340209-cecc5200-864e-11eb-9ca5-ca662e0d593c.jpg)
![output_mesh_param](https://user-images.githubusercontent.com/24324805/111340224-d3910600-864e-11eb-9547-7c0396c10803.jpg)
![rendered_mesh_param](https://user-images.githubusercontent.com/24324805/111340252-d986e700-864e-11eb-8e12-43daf0352ed9.jpg)

If you have any idea what could cause this let me know!

**Comment by mks0601** [comment]
I've just downloaded the repo and ran demo.
The results are below.
Please double check you followed the instruction carefully.

![rendered_mesh_param](https://user-images.githubusercontent.com/13601723/111349717-bb5bce00-86c4-11eb-8ffe-24989417c3e8.jpg)
![rendered_mesh_lixel](https://user-images.githubusercontent.com/13601723/111349726-bc8cfb00-86c4-11eb-8663-a0f7c53974b1.jpg)

**Comment by Yarp96** [comment]
Hi again,

Thanks for the fast answer but I found my mistake, I removed dataparallel thinking that It wouldnt affect the code but it actually messed up the predictions. Sorry for bothering!
