### ISSUE TITLE
The downloaded pre-trained model cannot be used，file cannot be unzipped

### ISSUE THREAD

**Issue by booker-max** [mks0601/I2L-MeshNet_RELEASE#52]
I downloaded you twice     
https://drive.google.com/drive/folders/14SJKZuCudli2xNN6pSh1bJepIZYlBfSE
I have tried various decompression methods for the file here, but it cannot be decompressed after the download is complete. Is there an error in the file you uploaded?
![image](https://user-images.githubusercontent.com/74257220/111250996-57e08a80-8649-11eb-97b3-7ba1c1238cc7.png)
![image](https://user-images.githubusercontent.com/74257220/111250878-164fdf80-8649-11eb-9be5-a41cd4745fd5.png)
![image](https://user-images.githubusercontent.com/74257220/111250905-25369200-8649-11eb-9dc8-9d6a5e21178b.png)
![image](https://user-images.githubusercontent.com/74257220/111250928-341d4480-8649-11eb-930b-09d556830755.png)

**Comment by mks0601** [comment]
I'm not a chines person. The snapshot files are not compressed. You can use them without uncompression.

**Comment by booker-max** [comment]
Thank you.
