### ISSUE TITLE
Why use Soft_argmax_1D functions, what is its role?

### ISSUE THREAD

**Issue by booker-max** [mks0601/I2L-MeshNet_RELEASE#53]
I am very interested in your work, I read your source code, I am thinking why you use the Soft_argmax_1D function，
1.In the PoseNet, you enter the heatMap_x to Soft_argmax_1D function, HeatMap_x.shape = [1, 29, 64], what is the value at each location？
2.Coord_x.shape = [1,29,1], what does Coord_x mean at each location? What is the ultimately want to get in the Lixel stage?
3.Why use the Soft_argmax function, what is the function of this function? I can understand the operation of each step in this function, but I can't understand why the output of the Soft_argmax function is the coord_x we want.
4.When in Demo, what are the difference between we choose Stage == "Lixel" and "stage" == "param"?

**Comment by mks0601** [comment]
Could you read the paper? All you asked are in the paper.
