### ISSUE TITLE
How to get the fitted parameters of SMPL by SMPLify-x with 3D coordinates from multi-view??

### ISSUE THREAD

**Issue by onepiece666** [mks0601/I2L-MeshNet_RELEASE#55]
I read your paper. It's great. I want to know the method to get the fitted parameters of SMPL by SMPLify-x with 3D coordinate from multi-view. I just know the way to fit through 2D coordinate from a image. Could you tell me about the datails or introduce me some paper about it . Thanks.

**Comment by mks0601** [comment]
I fitted SMPL to 3D world coordinates (not 2D coordinates).
The detailed descriptions will be available in my new paper (NeuralAnnot).
It is uploaded in arxiv, but will be updated soon and what you asked will be included in the updated version.
