### ISSUE TITLE
关于测试的问题？

### ISSUE THREAD

**Issue by booker-max** [mks0601/I2L-MeshNet_RELEASE#62]
您好，我想问一下您在Human3.6M测试集上提供的pose_coord_gt_h36m是通过Smplify-x预估出SMPL参数然后得到的么？
![image](https://user-images.githubusercontent.com/74257220/114333648-daca0780-9b59-11eb-9c5d-8c54b514188a.png)

**Comment by mks0601** [comment]
I'm not a Chinese person.
