### ISSUE TITLE
why not change the smpl_shape before   self.smpl.layer['neutral'](smpl_pose, smpl_shape)

### ISSUE THREAD

**Issue by zhLawliet** [mks0601/I2L-MeshNet_RELEASE#65]
smpl_mesh_coord, smpl_joint_coord = self.smpl.layer['neutral'](smpl_pose, smpl_shape)
# change to mean shape if beta is too far from it
smpl_shape[(smpl_shape.abs() > 3).any(dim=1)] = 0.

if the beta is error,the smpl_joint_coord will be error.
@mks0601

**Comment by mks0601** [comment]
You are right. However, I found that there is a marginal performance difference.

**Comment by zhLawliet** [comment]
@mks0601  Will there be conflicts when using orig_joint_cam and  fit_joint_cam together，I think it's better to just use fit_joint_cam , which fit for smpl.  Have you done an experiment about the orig_joint_cam and  fit_joint_cam.

**Comment by mks0601** [comment]
fit_joint_cam provides smpl joint coordinates. However, they have some fitting errors.
