### ISSUE TITLE
Where to download SMPL v1.0.0 neutral model?

### ISSUE THREAD

**Issue by buaacyw** [mks0601/I2L-MeshNet_RELEASE#69]
Thanks for your great work!
When I download the three SMPL v1.0.0 models from the SMPL project website, I find that there are only male and female models in v1.0.0.
![image](https://user-images.githubusercontent.com/52091468/118579885-784fd100-b7c1-11eb-8dc9-3de39e32b185.png)
I download from here.
So where to download the neutral model, thanks!

**Comment by mks0601** [comment]
You can download the neutral model at [here](http://smplify.is.tue.mpg.de/). I'll update the README.

**Comment by buaacyw** [comment]
Thanks for your quick apply！
