### ISSUE TITLE
the name of h36m images is not consistent with the raw data

### ISSUE THREAD

**Issue by GuiZhaoyang** [mks0601/I2L-MeshNet_RELEASE#7]
I have download the data from h36m website,but the name of the images does not consistent with the annotation provided by this code.Could I acquire how to match the name of the images?In addition, could I get the action and subaction dict for recording which action/subaction has the specific idx?

**Comment by mks0601** [comment]
You can download images from my README (https://drive.google.com/drive/folders/1kgVH-GugrLoc9XyvP6nRoaFpw3TmM5xK?usp=sharing)

**Comment by GuiZhaoyang** [comment]
@mks0601 Thanks, I get it.But the name of images seems processed.So, Could I get the code or the method how you process them from original data?

**Comment by mks0601** [comment]
You can just download all images and annotation files from google drive and there would be no problem because the images in the google drive are already processed (renamed).
If you want to process them by yourself, you can use this code (https://github.com/mks0601/3DMPPE_POSENET_RELEASE/tree/master/tool/Human36M)

**Comment by GuiZhaoyang** [comment]
@mks0601 Hi，I still have a question after checking the file you provide. I did not find the correspondence between cam_id  ([1,2,3,4]) and cam name of raw data ('54138969', '55011271' ,'58860488', '60457274').

**Comment by mks0601** [comment]
I wrapped all data into `.json` files. You can see the camera parameters identified by `cam_id` at `annotations.zip` from [here](https://drive.google.com/drive/u/1/folders/1kgVH-GugrLoc9XyvP6nRoaFpw3TmM5xK). Please check `Human36M_subject*_camera.json`.

**Comment by GuiZhaoyang** [comment]
@mks0601 I have checked Human36M_subject*_camera.json, but I only found the cam_id and its 'R','t','f','c'.And I still do not know which cam_id is '54138969', which is '55011271'.('54138969', '55011271' ,'58860488', '60457274'). So I want to know the cam_id correspond which name ('54138969', '55011271' ,'58860488', '60457274').

**Comment by mks0601** [comment]
I didn't save that information, but could you tell me why do you need that? All camera parameters are already available in my json files. If you want to know that, maybe you can just compare several images from camera '54138969' and my cam_id 0 images?

**Comment by GuiZhaoyang** [comment]
@mks0601 Because the dataset is so large that I don not want to download it again since I had have the h36m dataset which download from official network. But I want use your SMPL parameters, so I need to know the corresponding.

**Comment by mks0601** [comment]
54138969: cam_id 1
55011271: cam_id 2
58860488: cam_id 3
60457274: cam_id 4

**Comment by GuiZhaoyang** [comment]
thanks very much. I guess I could matching it. @mks0601
