### ISSUE TITLE
How to only predict the hand like the teaser?

### ISSUE THREAD

**Issue by buaacyw** [mks0601/I2L-MeshNet_RELEASE#70]
Thanks for your great work!
![image](https://user-images.githubusercontent.com/52091468/118598835-4f3f3880-b7e1-11eb-8f80-194b955fbaf1.png)
Could you please tell me how to predict the hand like this teaser?
![image](https://user-images.githubusercontent.com/52091468/118598984-7433ab80-b7e1-11eb-8118-301de5eed474.png)
I run demo.py on the image and get the above result. This is a (640,480) image and I have changed the box to (0,0,320,360).
All the model follows your installation instruction and run your input image well.
Thanks!

**Comment by mks0601** [comment]
demo code is only for the body. You should change it to use MANO.

**Comment by mks0601** [comment]
https://github.com/mks0601/I2L-MeshNet_RELEASE#freihand-dataset

**Comment by buaacyw** [comment]
Thanks for your quick reply!

**Comment by buaacyw** [comment]
https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/5d495593fa99e3e44af0289964a7da7284fd9876/demo/demo.py#L124
I'm not sure but do you mean that change this visualize function and the pre-trained model?
And why is mano needed? Function vis_img seems to be able to visualize hand mesh.
