### ISSUE TITLE
Ground truth mesh image correspondence

### ISSUE THREAD

**Issue by Shubhendu-Jena** [mks0601/I2L-MeshNet_RELEASE#71]
Hi,

Thank you for the great work. I had a small question about the data. For 3DPW and COCO, which has images with multiple people in it (even after cropping using the bounding box coordinates provided in your annotations), how did you decide which person to fit the mesh for? Attaching a cropped example for reference from the 3DPW dataset. I'd be grateful if you could let me know as I want to find out the correspondence between the person and the ground truth mesh for every image in COCO/3DPW datasets.

Thanks in advance :)  
![full2](https://user-images.githubusercontent.com/12934176/120085934-b1027b00-c0dc-11eb-80d9-c6d0dc4896e2.png)

**Comment by mks0601** [comment]
Sorry I can't get your question :( Both COCO and 3DPW provide annotations for each person. Could you ask your question again?

**Comment by Shubhendu-Jena** [comment]
Hi. Thank you for the quick response. My question is that for a particular image frame, I can see only one vector smpl shape (of size 10) and pose param (of size 72). However, there is more than one person in the image frame. This means that the mesh has been fit to one of the persons in the image frame. Is there a way to find which one that is?

**Comment by mks0601** [comment]
I see. You can find a person with a bounding box? There would be 'bbox' in 'ann'.

**Comment by Shubhendu-Jena** [comment]
Yes, I have seen that. In fact, the above image that I've posted is one I've obtained using the bbox coordinates that I obtained from ann['bbox']. However, clearly there are still 2 people in the image so I'm still confused about whether the mesh was fit to person 1 or person 2.

**Comment by mks0601** [comment]
I think you crop the image using extended ann['bbox'], not the original ann['bbox'].
The original ann['bbox'] is a tight box.

**Comment by Shubhendu-Jena** [comment]
Ah, yes you're right! Thank you so much. That takes care of my problems :)
