### ISSUE TITLE
Questions about H36M 2D joint coordinates 

### ISSUE THREAD

**Issue by frankjappa95** [mks0601/I2L-MeshNet_RELEASE#74]
First of all, thank you for releasing the SMPL parameters of Human3.6M datasets. 

If it doesn't bother you, would you please share the 2D keypoints information that was used for the fitting procedure?

I though that the annotations uploaded on Gdrive link contains 2D joint coordinate information, but I cannot find the 2D joint information nowhere. Both in SMPL_params annotations and joint_3d annotations there was 3D joint coordinate information, unless I got wrong, and in data annotations there were only kps_visibility and bbox information. 

I'd like to know if I do some mistakes, or if it doesn't, then is there any way to find the 2D joint coordinates of the shared images? 

Thank you in advance :)

**Comment by mks0601** [comment]
I fitted SMPL to GT 3D pose, not 2D pose.

**Comment by frankjappa95** [comment]
Thank you for the answer, I should've read your paper more in detail. 

If I get it right, can 2D joints information be obtained from the 3D GT coordinates(the one in joints_3d json e.g. Human36M_subject5_joint_3d.json), using camera extrinsic intrinsic and extrinsic parameters that you've uploaded? 

Thank you in advance again!

**Comment by mks0601** [comment]
Yes. You can obtain 2D joints from 3D GT coordinates using camera extrinsics/intrinsics.

**Comment by frankjappa95** [comment]
Thank you for the answer! I successfully obtained 2D joints from your dataset :>

**Comment by chh7411898** [comment]
> Thank you for the answer! I successfully obtained 2D joints from your dataset :>

can you share about get 2d joint code?

**Comment by frankjappa95** [comment]
@chh7411898 Sorry for the late answer! I'll upload the code at my github in a week :)

**Comment by frankjappa95** [comment]
@chh7411898 here is the file to get 2D key points! :)

**Comment by frankjappa95** [comment]
@chh7411898 I uploaded the code in my GitHub, so you can check it and also visualize it :)
