### ISSUE TITLE
Question about the deployment of "pyrender" package

### ISSUE THREAD

**Issue by XiaoqiangZhou** [mks0601/I2L-MeshNet_RELEASE#8]
Hi,  Gyeongsik, I read your I2L-MeshNet paper recently. This work is a really great and interesting work, and I hope to follow this work in the future.

However, when I tried to deploy the "pyrender" package in our GPU server, I met a problem. Could you please help me?

When I tried to run an easy commond: `import pyrender;pyrender.OffscreenRenderer(1,2,1)`, I got the error 

> File "/home/username/anaconda3/lib/python3.7/site-packages/pyrender/offscreen.py", line 149, in _create
>     self._platform.init_context()
> File "/home/username/anaconda3/lib/python3.7/site-packages/pyrender/platforms/pyglet_platform.py", line 45, in init_context
>     'internal error message was "{}"'.format(e)
> ValueError: Failed to initialize Pyglet window with an OpenGL >= 3+ context. If you're logged in via SSH, ensure that you're running your script with vglrun (i.e. VirtualGL). The internal error message was "Cannot connect to "None""

The GPU server is a remote machine and we log on it with SSH usually. I tried to follow the instruction in "pyrender“ to build osmesa from source code but failed.

I'm looking forward to know if you met this problem ever and how did you solve it? Could you please give me some suggestions?

Thanks.

**Comment by mks0601** [comment]
Hi, thanks for having interest in my work :) 
I also met this kind of error when I run my demo on GPU server via SSH, so I just ran the demo on my local machine.
Maybe you should use x server for this error?

**Comment by XiaoqiangZhou** [comment]
@mks0601 Thanks for your quick reply and kind suggestion. We will share our solution if we can solve it in the future.

**Comment by hot-dog** [comment]
@mks0601 I switched opengl's backend to egl or osmesa by setting os.environ["PYOPENGL_PLATFORM"] = "egl", the output_mesh_lixel and rendered_mesh_lixel is normal, but output_mesh_param and rendered_mesh_param is wrong, any suggestion?

**Comment by mks0601** [comment]
You'd better check whether you did exactly follow the instruction for the quick demo.

**Comment by hot-dog** [comment]
It seems that snapshot_12.pth.tar cause, when i use snapshot_8.pth.tar, the result is normal. And by the way, maybe you could update READ.me file, adding the followings:
1、install oemesa follow https://pyrender.readthedocs.io/en/latest/install/
2、reinstall the specific pyopengl fork: https://github.com/mmatl/pyopengl
3、set opengl's backend to egl or osmesa via os.environ["PYOPENGL_PLATFORM"] = "egl"
Then it can run on a headless server~~

**Comment by mks0601** [comment]
Got it. Thanks for such a valuable suggestion!
