### ISSUE TITLE
FreiHAND Training Settings

### ISSUE THREAD

**Issue by Bozcomlekci** [mks0601/I2L-MeshNet_RELEASE#82]
Greetings, 

While training on FreiHAND with train_batch_size=16 and num_gpus=3, I obtained the following results:

`PA MPJPE=10.2 mm 
PA MPVPE=10.3 mm
F_aligned@5.0mm=0.555
F_aligned@15.0mm=0.941`

The rest of the parameters for training are same with your implementation. I couldn't understand why I obtained the results above instead of the results reported in the paper. Are the default parameter settings implemented applicable for a training on FreiHAND dataset as well? For FreiHAND, what were your training settings such as the values of train_batch_size and num_gpus?

Thanks in advance.

**Comment by mks0601** [comment]
Did you use lixel stage? param stage?

**Comment by Bozcomlekci** [comment]
> Did you use lixel stage? param stage?

Lixel stage

**Comment by mks0601** [comment]
That is weird. Actually, train_batch_size and num_gpus marginally affect the performance.
Did you train trainset_3d=['FreiHAND'], trainset_2d=[], testset='FreiHAND' in config.py?

**Comment by Bozcomlekci** [comment]
> That is weird. Actually, train_batch_size and num_gpus marginally affect the performance.
> Did you train trainset_3d=['FreiHAND'], trainset_2d=[], testset='FreiHAND' in config.py?

Yes, I set them as you describe.

I'll do it all from scratch. If the training settings are same with yours, I guess there is something that I changed and didn't notice.

**Comment by mks0601** [comment]
Got it. Let me know if you have some problems.

**Comment by Bozcomlekci** [comment]
Greetings,
It seems that the issue was due to a omitted code block which performs weight initialization. Thanks for the help.
