### ISSUE TITLE
Question regarding augmentation

### ISSUE THREAD

**Issue by Shubhendu-Jena** [mks0601/I2L-MeshNet_RELEASE#83]
Hi,

I noticed something peculiar in the augmentation part and hence, I'd be graetful if you could clarify this for me. Basically, in your dataset class (for example in Human36M.py), when you do rotation augmentation for the image (variable rot in degrees in your code), you're not doing the same to your image aligned mesh/joint data (h36m_joint_img, smpl_mesh_img and smpl_joint_img). Instead, only the camera space joints (smpl_joint_cam) are augmented using "rot_aug_mat" matrix. Shouldn't the augmentation be also done for h36m_joint_img, smpl_mesh_img and smpl_joint_img?

Thanks

**Comment by mks0601** [comment]
https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/754e0201e494dc891b94949098cc93eec0e37ee8/data/Human36M/Human36M.py#L257
https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/754e0201e494dc891b94949098cc93eec0e37ee8/data/Human36M/Human36M.py#L283

are doing affine transformation.

**Comment by Shubhendu-Jena** [comment]
Ah, thank you! Got it. Sorry for the confusion. Closing now.
