### ISSUE TITLE
how do you test your inference time?

### ISSUE THREAD

**Issue by KHao123** [mks0601/I2L-MeshNet_RELEASE#85]
I test your model with the speed_test in [https://github.com/facebookresearch/LeViT/blob/main/speed_test.py](url).
And get the result of 
![image](https://user-images.githubusercontent.com/42881653/129312172-76f9cae1-d1d4-4dcd-88ed-349688ee56d5.png)
300 fps on 2080ti and 0.42 fps on cpu, which is inconsistent with your 25 fps.
Do you get the inference time on GPU or CPU？
Thank you.

**Comment by mks0601** [comment]
The time is measured on a single RTX 2080Ti GPU with batch size 1.
