### ISSUE TITLE
visualization of Human3.6

### ISSUE THREAD

**Issue by KHao123** [mks0601/I2L-MeshNet_RELEASE#86]
Hi, sorrry to disturb you.
I meet a bug when visualizing Human3.6 with the code:
![image](https://user-images.githubusercontent.com/42881653/129673547-63927c00-ad5f-44c2-8a91-bdd4b5f4cace.png)
The mesh and object are visualized correctly, while the render mesh show nothing in the output image.
But it works in PW3D.

**Comment by mks0601** [comment]
please check mesh_out_cam is in the correct place. It should not be a root-relative coordinate.

**Comment by KHao123** [comment]
The code to mesh_out_cam remain unchanged.
It seems something wrong in the evaluation function.
I divide the mesh_out_cam with 1000000 and it works.
