### ISSUE TITLE
Visualization of fit_joint_cam

### ISSUE THREAD

**Issue by Bozcomlekci** [mks0601/I2L-MeshNet_RELEASE#93]
Greetings,
I'm trying to visualize the joints via `fit_joint_cam`.  I use `vis_keypoints(img, kps, alpha=1)` function in `common/utils/vis.py`. I get empty image results. Am I doing something wrong? Could you tell the input shapes for the arguments of the function (img and kps). Can I input `fit_joint_cam` as `kps`?

**Comment by mks0601** [comment]
fit_joint_cam are defined in camera-centered coordinate system, which has a milimeter (or meter) unit. You should project them to image space before trying to visualize them. The projected one is fit_joint_img.

**Comment by Bozcomlekci** [comment]
Thanks for the explanation, I have corrected it.
