### ISSUE TITLE
Freihand annotation differs from the original anotation

### ISSUE THREAD

**Issue by biansy000** [mks0601/I2L-MeshNet_RELEASE#96]
Hello, after I download the freihand annotation you provided [here](https://drive.google.com/drive/folders/1QGWu_nWi5eyrWSkPEOMyK1tAGFWRXQjC), I find that the annotation is almost the same with the original dataset I downloaded from [freihand](https://lmb.informatik.uni-freiburg.de/resources/datasets/FreihandDataset.en.html), except that the first three items of theta (refers to global orientation) are different. Is it possible for you to explain why the difference exists? Thanks if you could help.

**Comment by mks0601** [comment]
Hi,

In the original annotation, I remember that the global rotation is a rotation to world coordinate system.
I changed that to a rotation to camera coordinate system.

**Comment by biansy000** [comment]
Could you explain how the rotation is derived? As I do not see any available information in the original dataset I downloaded from [freihand](https://lmb.informatik.uni-freiburg.de/resources/datasets/FreihandDataset.en.html).

**Comment by mks0601** [comment]
They provide 3D hand joint coordinates in camera-centered coordinate system. I rigidly align the mesh to the 3D joint coordinates.

**Comment by biansy000** [comment]
I understand the process now, thanks
