### ISSUE TITLE
 H36m preprocessing file Require

### ISSUE THREAD

**Issue by MooreManor** [mks0601/I2L-MeshNet_RELEASE#98]
Hello. Thanks for your great work!
It seemed that I missed the preprocessing file of changing videos in h36m to images whose format is like `s_01_act_02_subact_01_ca_01*.jpg` and generating corresponding JSON files like `Human36M_subject*_data.json`.
I have the video of those images but I don’t have the preprocessing file to change the video to images. Can you offer the preprocessing files? Thanks!

**Comment by mks0601** [comment]
You can download pre-processed files in [here](https://github.com/mks0601/I2L-MeshNet_RELEASE#data)

**Comment by MooreManor** [comment]
Would you be pleased to offer the parsing code of that? Because I have the source videos and annotations of that. Downloading all files from Google Drive is slow and may have download failure for a huge file. Thanks!

**Comment by mks0601** [comment]
Maybe you sent the mail? I have replied. Thanks!

**Comment by MooreManor** [comment]
Okay! That's fine. I got it. Thanks a lot!

**Comment by MooreManor** [comment]
@mks0601 Is this the parsing code to generate pics? [H36M-Toolbox](https://github.com/CHUNYUWANG/H36M-Toolbox)
